spring.application.name=books-archive
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.datasource.username=books_archive
spring.datasource.password=books_archive
spring.datasource.url=jdbc:postgresql://localhost:5432/books_archive
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
